### ISSUE TITLE
You gained 0 exp

### ISSUE THREAD

**Issue by Septharoth** [ethanmoffat/EndlessClient#13] opened 2015-04-26 19:14 UTC
Killing an NPC client tells me "You gained 0 exp" but clearly gained 7.  Am sure it's something I'm overlooking, maybe Ethan will solve it easier than I.

**Comment by ethanmoffat** [comment] 2015-04-26 21:26
I think I've seen this happen before but I'm not sure of the exact conditions to reproduce it.

**Comment by Septharoth** [comment] 2015-04-26 22:58
Yeah, I'm still looking myself, can't quite find it.

Also, the XNA 4.0 Refresh link in your build guide on the post is an old or invalid link.  add me on Skype, just search for my name "Septharoth"  I've got an EO Related picture as my Display.  :P

**Comment by ethanmoffat** [comment] 2015-08-29 07:32
I'm going to close this since I haven't seen it happen in a long time. Might be a fluke on either end, invalid configuration, etc.

**Closed by ethanmoffat** 2015-08-29 07:32 UTC
Labels: bug
