### ISSUE TITLE
Crash upon connecting to game.eoserv.net

### ISSUE THREAD

**Issue by iDanScott** [ethanmoffat/EndlessClient#43] opened 2015-12-06 15:42 UTC
System.NullReferenceException: Object reference not set to an instance of an object.
   at EndlessClient.World.ApplyWelcomeMessage(WelcomeMessageData data)
   at EndlessClient.EOGame.<>c__DisplayClass33.<CharModButtonPress>b__2b(Object dlgS, CloseDialogEventArgs dlgE)
   at XNAControls.XNADialog.Close(XNAButton whichButton, XNADialogResult result)
   at EndlessClient.EOConnectingDialog.<Update>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)

**Comment by ethanmoffat** [comment] 2015-12-07 20:18
This is a known issue due to a race condition when logging in. Usually works after a couple login attempts. Currently I'm unsure the best way to solve it without some complex, convoluted locking mechanism to ensure the welcome packets are never handled out of order.

**Comment by dgadelha** [comment] 2015-12-15 01:58
Confirmed with MonoGame too:
   at XNAControls.XNAControl.Update(GameTime gameTime)
   at XNAControls.XNAButton.Update(GameTime gt)
   at Microsoft.Xna.Framework.Game.<.cctor>b__19(IUpdateable updateable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at EndlessClient.Program.Main() on Z:\github.com\ethanmoffat\EndlessClient\EndlessClient\EndlessClient\Program.cs:line 22

**Comment by ethanmoffat** [comment] 2016-05-07 23:07
Closing due to client rewrite

**Closed by ethanmoffat** 2016-05-07 23:07 UTC
Labels: bug
